# Fund this project via PayPal donation

custom: ['https://www.paypal.com/donate/?business=RX2YGW6MLJBQJ&no_recurring=0&item_name=Im+a+developer+from+Ukraine.+Russia+started+war+in+my+country+and+I+had+to+move+from+city+Chernihiv.++Donate+to+help+my+family.&currency_code=USD']
